/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contables;

import datos.acceso.CuentaFacade;
import datos.definiciones.Cuenta;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ngochez
 */
public final class VerCatalogo extends javax.swing.JFrame {
    
    CuentaFacade cuenta= new CuentaFacade();
    Cuenta c = new Cuenta();
    DefaultTableModel tablaCatalogo = new DefaultTableModel();
    
     
    /**
     * Creates new form VerCatalogo
     */
    public VerCatalogo() {
        initComponents();
        
        tablaCatalogo = (DefaultTableModel)JTCatalogo.getModel();
        CargarDatos();
        btnClean.setEnabled(false);
    }
    public void CargarDatos(){
    List<Cuenta> lista = cuenta.findAll();
    //Object [] datos= new Object[cuenta.count()];
      //  for (Cuenta cuenta1 : lista) {
        //    datos[Integer.parseInt(cuenta1.toString())]=cuenta1.getCuentaList();
          // tablaCatalogo.addRow(datos);
        //}
        //JTCatalogo.setModel(tablaCatalogo);
        for (Cuenta cuenta1 : lista) {
            Object[] fila = new Object[5];
            fila[0]=""+cuenta1.getIdCuenta();
            fila[1]=cuenta1.getNombreCuenta();
            fila[2]=cuenta1.getDescripcionCuenta();
            fila[3]=cuenta1.getIdCuentaPadre().getNombreCuenta();
            fila[4]=cuenta1.getTipoCuenta();
        tablaCatalogo.addRow(fila);
            
        }
        
    }
    
    public void  limpiarDatos(){
        //for (int i = 0; i < cuenta.count(); i++) {
          //  tablaCatalogo.removeRow(i);
            //i-=1;
        //}
        while (tablaCatalogo.getRowCount() > 0) 
        {
        tablaCatalogo.removeRow(0);
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTCatalogo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtBuscarCata = new javax.swing.JTextField();
        btnSalirCat = new javax.swing.JButton();
        btnBuscarCuenta = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Serif", 1, 18)); // NOI18N
        jLabel1.setText("Catálogo de cuentas.");

        JTCatalogo.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        JTCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID CUENTA", "NOMBRE CUENTA", "DESCRIPCION", "CUENTA PADRE", "TIPO CUENTA"
            }
        ));
        jScrollPane1.setViewportView(JTCatalogo);

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel2.setText("BUSCAR POR ID:");

        btnSalirCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/salir.png"))); // NOI18N
        btnSalirCat.setText("Salir");
        btnSalirCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirCatActionPerformed(evt);
            }
        });

        btnBuscarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        btnBuscarCuenta.setText("Buscar");
        btnBuscarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCuentaActionPerformed(evt);
            }
        });

        btnClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/clean.png"))); // NOI18N
        btnClean.setText("Limpiar busqueda");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(291, 291, 291))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSalirCat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(33, 33, 33)
                                .addComponent(txtBuscarCata, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarCuenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(35, 35, 35)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBuscarCata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCuenta)
                    .addComponent(btnClean))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnSalirCat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirCatActionPerformed
 int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea salir?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if(resp==0){
        dispose();
        }else{
        this.setVisible(true);
        }    }//GEN-LAST:event_btnSalirCatActionPerformed

    private void btnBuscarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCuentaActionPerformed
        limpiarDatos();
        
        if (txtBuscarCata.getText().isEmpty()) {
            CargarDatos();
        JOptionPane.showMessageDialog(null, "Ingrese el ID de la cuenta para generar la búsqueda");
        }else{
            int busqueda;    
        busqueda=Integer.parseInt(txtBuscarCata.getText());
            if(cuenta.find(busqueda)!=null){
            c=cuenta.find(busqueda);
            Object[] fila = new Object[5];
            fila[0]=""+c.getIdCuenta();
            fila[1]=c.getNombreCuenta();
            fila[2]=c.getDescripcionCuenta();
            fila[3]=c.getIdCuentaPadre().getNombreCuenta();
            fila[4]=c.getTipoCuenta();
        tablaCatalogo.addRow(fila);
        btnClean.setEnabled(true);

            }
            else{
        JOptionPane.showMessageDialog(null, "No se encontraron resultados de la busqueda");
        CargarDatos();
        }
        }
    }//GEN-LAST:event_btnBuscarCuentaActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        limpiarDatos();
        txtBuscarCata.setText("");
        CargarDatos();

    }//GEN-LAST:event_btnCleanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerCatalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTCatalogo;
    private javax.swing.JButton btnBuscarCuenta;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnSalirCat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscarCata;
    // End of variables declaration//GEN-END:variables
}
